name: Morning Debrief

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  update_metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Update Script
      run: python update_metadata.py

    - name: Commit and Push CSV
      run: |
        git pull
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/player_metadata.csv
        git add utils/name_map_suggestions_2k.json
        git commit -m "Update player metadata"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

  morning_debrief:
    runs-on: ubuntu-latest

    needs: update_metadata

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Debrief Script
      env:
          GMAIL_APP_KEY: ${{ secrets.GMAIL_APP_KEY }}
      run: python morning_debrief.py

    - name: Commit and Push CSV
      run: |
        git pull
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/first_basket_2025.csv
        git add data/rosters.nosync/rosters_2025.csv
        git commit -m "Update first basket and rosters table"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}


  schedule_today_games:
    runs-on: ubuntu-latest

    needs: morning_debrief

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.YML_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scheduler Script
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      run: python schedule_today_games.py

    - name: Push All Changes
      run: |
        git pull
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Updating metadata, game stats, scheduling today's games"
        git push https://x-access-token:${{ secrets.YML_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
